### ISSUE TITLE
Docker images always rebuilt when using ACR

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/hub23-deploy#13]
## Detailed set-up

```
# Setting up Kubernetes cluster
az login --output none
az account list --refresh --output table
az account set -s "Azure Pass - Sponsorship"
az group create --name acr-test --location westeurope --output table

mkdir acr-test && cd acr-test
ssh-keygen -f ssh-key-acrcluster

az aks create --name acrcluster \
              --resource-group acr-test \
              --ssh-key-value ssh-key-acrcluster.pub \
              --node-count 3 \
              --node-vm-size Standard_D2s_v3 \
              --output table

az aks get-credentials --name acrcluster --resource-group acr-test
kubectl get nodes

# Setup Helm
kubectl --namespace kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller --wait

kubectl patch deployment tiller-deploy \
        --namespace=kube-system \
        --type=json --patch='[{
                "op": "add",
                "path": "/spec/template/spec/containers/0/command",
                "value": ["/tiller", "--listen=localhost:44134"
        ]}]'

helm version
```

#### Setup BinderHub
```
openssl rand -hex 32
openssl rand -hex 32
```
Use outputs of above as `apiToken` and `secretToken` in `secret.yaml`.
Then connect it to a DockerHub account.

Create `config.yaml`.

```
# Install BinderHub:
helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
helm repo update

helm install jupyterhub/binderhub --version=0.2.0-3dd5511 --name=binderhub --namespace=binderhub -f secret.yaml -f config.yaml`

kubectl get svc proxy-public --namespace binderhub  # Add the output External IP to `config.yaml` under `hub_url` key.

helm upgrade binderhub jupyterhub/binderhub --version=0.2.0-3dd5511 -f secret.yaml -f config.yaml

kubectl get svc binder --namespace binderhub
```

Test BinderHub with: https://github.com/binder-examples/requirements

All good!

```
# Swap DockerHub for ACR
az acr create --name binderhubregistry --resource-group acr-test --sku Basic --output table
az acr login --name binderhubregistry

acrLogin=$(az acr list --resource-group acr-test --query "[].{acrLoginServer:loginServer}" --output tsv)
registryID=$(az acr show --name binderhubregistry --query id --output tsv)
password=$(az ad sp create-for-rbac --name scr-sp --role AcrPush --scopes $registryID --query password --output tsv)
clientID=$(az ad sp show --id http://scr-sp --query appId --output tsv)
```

Update `secret.yaml`.
```
registry:
  url: https://binderhubregistry.azurecr.io
  username: $clientID
  password: $password
```

Update `config.yaml`.
```
config:
  BinderHub:
    use_registry: true
    image_prefix: binderhubregistry.azurecr.io/<prefix>-
    hub_url: http://xx.xx.xx.xx
  DockerRegistry:
    token_url: "https://binderhubregistry.azurecr.io/oauth2/token?service=binderhubregistry.azurecr.io"

jupyterhub:
  hub:
    imagePullSecret:
      enabled: true
      registry: binderhubregistry.azurecr.io
      username: $clientID
      password: $password
```

`helm upgrade binderhub jupyterhub/binderhub --version=0.2.0-3dd5511 -f secret.yaml -f config.yaml`
