### ISSUE TITLE
Hub23 Binder launch fails: User already has a server running

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/hub23-deploy#17]
### Summary

An authenticated user gets a named pod on the Kubernetes cluster. This mean if they try to relaunch a Binder or launch a new Binder without either:

* waiting for the culler to cull their inactive pod, or
* stopping the server themselves through the Control Panel of the Notebook environment,

they will receive the following launch error:

```
Found built image, launching...
Launching server...
Launch attempt 1 failed, retrying...
Launch attempt 2 failed, retrying...
Launch attempt 3 failed, retrying...
User <username> already has a running server.
```

<details><summary>Config below</summary>

```
config:
  BinderHub:
    use_registry: true
    image_prefix: <image-prefix>-
    hub_url: http://<jupyter-ip>
    auth_enabled: true

jupyterhub:
  cull:
    every: 660
    timeout: 600
    maxAge: 21600

  hub:
    services:
      binder:
        oauth_redirect_uri: "http://<binder-ip>/oauth_callback"
        oauth_client_id: "binder-oauth-client-test"
    extraConfig:
      hub_extra: |
        c.JupyterHub.redirect_to_server = False

      binder: |
        from kubespawner import KubeSpawner

        class BinderSpawner(KubeSpawner):
          def start(self):
              if 'image' in self.user_options:
                # binder service sets the image spec via user options
                self.image = self.user_options['image']
              return super().start()
        c.JupyterHub.spawner_class = BinderSpawner

  singleuser:
    cmd: jupyterhub-singleuser

  auth:
    type: github
    github:
      clientId: "xxxx"
      clientSecret: "xxxx"
      callbackUrl: "http://<jupyter-ip>/hub/oauth_callback"
      orgWhitelist:
        - "binderhub-test-org"
    scopes:
      - "read:user"
```
</details>

https://discourse.jupyter.org/t/binder-failed-to-launch-user-already-has-a-server-running/929

### What needs to be done?

- [ ] Try to mitigate this

### Who can help?

* Binder team

---
