### ISSUE TITLE
Dependencies to add to Hub23 Helm Chart

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/hub23-deploy#41]
```yaml
 - name: nginx-ingress
   version: 0.20.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: prometheus
   version: 7.4.4
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: grafana
   version: 1.18.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: kube-lego
   version: 0.4.2
   repository: https://kubernetes-charts.storage.googleapis.com
```
