### ISSUE TITLE
Deployment to change Binder logo crashing pod on autoscaling Hub

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/hub23-deploy#5]
## Summary

The following config was added to change the logo on the Binder page of an autoscaling BinderHub (from [these docs](https://binderhub.readthedocs.io/en/latest/customizing.html#template-customization)):

```
config:
  BinderHub:
    template_path: /etc/binderhub/custom/templates
    extra_static_path: /etc/binderhub/custom/static
    extra_static_url_prefix: /extra_static/
    template_variables:
      EXTRA_STATIC_URL_PREFIX: "/extra_static/"

initContainers:
  - name: git-clone-templates
    image: alpine/git
    args:
      - clone
      - --single-branch
      - --branch=feature/auto-config-scripts
      - --depth=1
      - https://github.com/alan-turing-institute/hub23-deploy/
      - /etc/binderhub/custom
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: custom-templates
        mountPath: /etc/binderhub/custom
extraVolumes:
  - name: custom-templates
    emptyDir: {}
extraVolumeMounts:
  - name: custom-templates
    mountPath: /etc/binderhub/custom
```

This config has shown to work on a non-autoscaling BinderHub, however on an autoscaling BinderHub it is causing the following issue with the Kubernetes pods:

```
NAME                        READY   STATUS                  RESTARTS   AGE
binder-6f9765b848-blh5h     0/1     Init:CrashLoopBackOff   8          16m
```

This is a repeated failure to initialise
