### ISSUE TITLE
Where did the PAT go?!

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/hub23-deploy#70]
Somewhere during the migration to a local helm chart, the GitHub PAT the increases the rate limitation seems to have wandered off.

**Comment by sgibson91** [comment]
```
jupyterhub:
  config:
    GitHubRepoProvider:
      access_token: <accessToken>
```
