### ISSUE TITLE
Trying to redeploy Hub23 after EduHub migration

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/hub23-deploy#79]
Following these docs: https://discourse.jupyter.org/t/wip-documentation-about-cert-manager/2068/2

## Starting Point

`hub23-chart/requirements.yaml`:

```
dependencies:
- name: binderhub
  repository: https://jupyterhub.github.io/helm-chart
  version: 0.2.0-1efa7b8
```

`hub23-chart/values.yaml`:

```
rbac:
  enabled: true

letsencrypt:
    contactEmail: sgibson@turing.ac.uk

binderhub:
  config:
    BinderHub:
      use_registry: true

      template_path: /etc/binderhub/custom/templates
      extra_static_path: /etc/binderhub/custom/static
      extra_static_url_prefix: /extra_static/
      template_variables:
        EXTRA_STATIC_URL_PREFIX: "/extra_static/"

  initContainers:
    - name: git-clone-templates
      image: alpine/git
      args:
        - clone
        - --single-branch
        - --branch=master
        - --depth=1
        - --
        - https://github.com/alan-turing-institute/hub23-deploy
        - /etc/binderhub/custom
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: custom-templates
          mountPath: /etc/binderhub/custom
  extraVolumes:
    - name: custom-templates
      emptyDir: {}
  extraVolumeMounts:
    - name: custom-templates
      mountPath: /etc/binderhub/custom
```

`deploy/prod.yaml`:

```
projectName: hub23

binderhub:
  config:
    BinderHub:
      image_prefix: hub23registry.azurecr.io/hub23/binder-dev-

    DockerRegistry:
      token_url: "https://hub23registry.azurecr.io/oauth2/token?service=hub23registry.azurecr.io"

  registry:
    url: https://hub23registry.azurecr.io

  jupyterhub:
    cull:
      every: 660
      timeout: 600
      maxAge: 21600  # maxAge is 6 hours: 6 * 3600 = 21600

    singleuser:
      memory:
        limit: 1G
        guarantee: 1G
      cpu:
        limit: .5
        guarantee: .5

    prePuller:
      continuous:
        enabled: true

    scheduling:
      podPriority:
        enabled: true
      userPlaceholder:
        replicas: 3
      userScheduler:
        enabled: true
```

`.secret/prod.yaml`:

```
binderhub:
  registry:
    username: xxxx
    password: xxxx

  jupyterhub:
    hub:
      services:
        binder:
          apiToken: "xxxx"
    proxy:
      secretToken: "xxxx"
```

**Comment by sgibson91** [comment]
## Step 1

Update helm chart dependencies with: `cd hub23-chart && helm dependency update && cd ..`

Install `hub23-chart` with following command:

```
helm install ./hub23-chart --name hub23 --namespace hub23 -f deploy/prod.yaml -f .secret/prod.yaml
```

Find JupyterHub External IP: `kubectl get svc proxy-public -n hub23`

Add following to `deploy/prod.yaml`: `hub_url: http://xx.xx.xx.xx`

Perform helm upgrade with the following command:

```
helm upgrade hub23 ./hub23-chart -f deploy/prod.yaml -f .secret/prod.yaml
```

Find Binder IP: `kubectl get svc binder -n hub23`

Check BinderHub works: ✅

**Comment by sgibson91** [comment]
## Step 2

Add `nginx-ingress` and `cert-manager` dependencies to `requirements.yaml`:

```
dependencies:
- name: binderhub
  repository: https://jupyterhub.github.io/helm-chart
  version: 0.2.0-1efa7b8
- name: nginx-ingress	
  repository: https://kubernetes-charts.storage.googleapis.com	
  version: 1.24.3	
- name: cert-manager	
  repository: https://charts.jetstack.io	
  version: v0.11.0
```

Add the `cert-manager` helm repo: `helm repo add cert-manager https://charts.jetstack.io`

Perform helm upgrade:

```
cd hub23-chart && helm dependency update && cd ..
helm upgrade hub23 ./hub23-chart -f deploy/prod.yaml -f .secret/prod.yaml
```

Check BinderHub still works: ✅ BUT ❗️ 

```
NAME                                                  READY   STATUS             RESTARTS   AGE
hub23-cainjector-66fb97b4c9-7lw9j                     0/1     CrashLoopBackOff   2          48s
```

Output of `kubectl describe pod hub23-cainjector-66fb97b4c9-7lw9j -n hub23`:

```
Name:           hub23-cainjector-66fb97b4c9-7lw9j
Namespace:      hub23
Priority:       0
Node:           aks-nodepool1-40514338-vmss000001/10.240.0.5
Start Time:     Mon, 14 Oct 2019 21:15:06 +0100
Labels:         app=cainjector
                app.kubernetes.io/instance=hub23
                app.kubernetes.io/managed-by=Tiller
                app.kubernetes.io/name=cainjector
                helm.sh/chart=cainjector-v0.11.0
                pod-template-hash=66fb97b4c9
Annotations:    <none>
Status:         Running
IP:             10.244.0.43
IPs:            <none>
Controlled By:  ReplicaSet/hub23-cainjector-66fb97b4c9
Containers:
  cainjector:
    Container ID:  docker://3b4eda4a7cf708407de9cb58131a16fa7a072a868444f59d4c9421c14b30e7eb
    Image:         quay.io/jetstack/cert-manager-cainjector:v0.11.0
    Image ID:      docker-pullable://quay.io/jetstack/cert-manager-cainjector@sha256:cf77d14d1c825190a38ac6b593f591998e3b34464f626f24479eb3e21dd589b3
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=2
      --leader-election-namespace=kube-system
    State:          Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Mon, 14 Oct 2019 21:16:47 +0100
      Finished:     Mon, 14 Oct 2019 21:16:49 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Mon, 14 Oct 2019 21:16:03 +0100
      Finished:     Mon, 14 Oct 2019 21:16:05 +0100
    Ready:          False
    Restart Count:  4
    Environment:
      POD_NAMESPACE:  hub23 (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from hub23-cainjector-token-dwx48 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  hub23-cainjector-token-dwx48:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub23-cainjector-token-dwx48
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From                                        Message
  ----     ------     ----               ----                                        -------
  Normal   Scheduled  105s               default-scheduler                           Successfully assigned hub23/hub23-cainjector-66fb97b4c9-7lw9j to aks-nodepool1-40514338-vmss000001
  Normal   Pulled     5s (x5 over 103s)  kubelet, aks-nodepool1-40514338-vmss000001  Container image "quay.io/jetstack/cert-manager-cainjector:v0.11.0" already present on machine
  Normal   Created    5s (x5 over 102s)  kubelet, aks-nodepool1-40514338-vmss000001  Created container cainjector
  Normal   Started    4s (x5 over 102s)  kubelet, aks-nodepool1-40514338-vmss000001  Started container cainjector
  Warning  BackOff    1s (x7 over 95s)   kubelet, aks-nodepool1-40514338-vmss000001  Back-off restarting failed container
```

**Comment by sgibson91** [comment]
## Step 3

Add following configuration to `values.yaml`:

```
nginx-ingress:
  controller:
    config:
      proxy-body-size: 64m

cert-manager:
  ingressShim:
    defaultIssuerName: "staging"
    defaultIssuerKind: "ClusterIssuer"
    defaultACMEChallengeType: "http01"
```

Perform a helm upgrade:

```
cd hub23-chart && helm dependency update && cd ..
helm upgrade hub23 ./hub23-chart -f deploy/prod.yaml -f .secret/prod.yaml
```

Check if BinderHub still works: ✅BUT ❗️

```
NAME                                                  READY   STATUS             RESTARTS   AGE
hub23-cainjector-66fb97b4c9-7lw9j                     0/1     CrashLoopBackOff   6          9m1s
hub23-cert-manager-698b56f675-m2tmf                   0/1     CrashLoopBackOff
```

Output of `kubectl describe pod hub23-cainjector-66fb97b4c9-7lw9j -n hub23`:

```
Name:           hub23-cainjector-66fb97b4c9-7lw9j
Namespace:      hub23
Priority:       0
Node:           aks-nodepool1-40514338-vmss000001/10.240.0.5
Start Time:     Mon, 14 Oct 2019 21:15:06 +0100
Labels:         app=cainjector
                app.kubernetes.io/instance=hub23
                app.kubernetes.io/managed-by=Tiller
                app.kubernetes.io/name=cainjector
                helm.sh/chart=cainjector-v0.11.0
                pod-template-hash=66fb97b4c9
Annotations:    <none>
Status:         Running
IP:             10.244.0.43
IPs:            <none>
Controlled By:  ReplicaSet/hub23-cainjector-66fb97b4c9
Containers:
  cainjector:
    Container ID:  docker://54c51a9f59724e2cc70b0885b20a783c1618e72524e112d55ee7ed89c3e0c430
    Image:         quay.io/jetstack/cert-manager-cainjector:v0.11.0
    Image ID:      docker-pullable://quay.io/jetstack/cert-manager-cainjector@sha256:cf77d14d1c825190a38ac6b593f591998e3b34464f626f24479eb3e21dd589b3
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=2
      --leader-election-namespace=kube-system
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Mon, 14 Oct 2019 21:21:05 +0100
      Finished:     Mon, 14 Oct 2019 21:21:08 +0100
    Ready:          False
    Restart Count:  6
    Environment:
      POD_NAMESPACE:  hub23 (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from hub23-cainjector-token-dwx48 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  hub23-cainjector-token-dwx48:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub23-cainjector-token-dwx48
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                     From                                        Message
  ----     ------     ----                    ----                                        -------
  Normal   Scheduled  9m51s                   default-scheduler                           Successfully assigned hub23/hub23-cainjector-66fb97b4c9-7lw9j to aks-nodepool1-40514338-vmss000001
  Normal   Pulled     8m11s (x5 over 9m49s)   kubelet, aks-nodepool1-40514338-vmss000001  Container image "quay.io/jetstack/cert-manager-cainjector:v0.11.0" already present on machine
  Normal   Created    8m11s (x5 over 9m48s)   kubelet, aks-nodepool1-40514338-vmss000001  Created container cainjector
  Normal   Started    8m10s (x5 over 9m48s)   kubelet, aks-nodepool1-40514338-vmss000001  Started container cainjector
  Warning  BackOff    4m43s (x23 over 9m41s)  kubelet, aks-nodepool1-40514338-vmss000001  Back-off restarting failed container
```

Output of `kubectl describe pod hub23-cert-manager-698b56f675-m2tmf -n hub23`:

```
Name:           hub23-cert-manager-698b56f675-m2tmf
Namespace:      hub23
Priority:       0
Node:           aks-nodepool1-40514338-vmss000000/10.240.0.4
Start Time:     Mon, 14 Oct 2019 21:22:33 +0100
Labels:         app=cert-manager
                app.kubernetes.io/instance=hub23
                app.kubernetes.io/managed-by=Tiller
                app.kubernetes.io/name=cert-manager
                helm.sh/chart=cert-manager-v0.11.0
                pod-template-hash=698b56f675
Annotations:    prometheus.io/path: /metrics
                prometheus.io/port: 9402
                prometheus.io/scrape: true
Status:         Running
IP:             10.244.2.64
IPs:            <none>
Controlled By:  ReplicaSet/hub23-cert-manager-698b56f675
Containers:
  cert-manager:
    Container ID:  docker://8f085fe24ad15041c0530ba0ad2352c720240a971d9960c6f26ea6e795efb4df
    Image:         quay.io/jetstack/cert-manager-controller:v0.11.0
    Image ID:      docker-pullable://quay.io/jetstack/cert-manager-controller@sha256:f7a1add1958ec48d96a417336fb4c62a80c3a0f71906e1b1e5b719b6f2d2d4dc
    Port:          9402/TCP
    Host Port:     0/TCP
    Args:
      --v=2
      --cluster-resource-namespace=$(POD_NAMESPACE)
      --leader-election-namespace=kube-system
      --default-issuer-name=staging
      --default-issuer-kind=ClusterIssuer
      --default-acme-issuer-challenge-type=http01
      --webhook-namespace=$(POD_NAMESPACE)
      --webhook-ca-secret=hub23-cert-manager-webhook-ca
      --webhook-serving-secret=hub23-cert-manager-webhook-tls
      --webhook-dns-names=hub23-cert-manager-webhook,hub23-cert-manager-webhook.hub23,hub23-cert-manager-webhook.hub23.svc
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Mon, 14 Oct 2019 21:25:33 +0100
      Finished:     Mon, 14 Oct 2019 21:25:33 +0100
    Ready:          False
    Restart Count:  5
    Environment:
      POD_NAMESPACE:  hub23 (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from hub23-cert-manager-token-llbp5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  hub23-cert-manager-token-llbp5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub23-cert-manager-token-llbp5
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                                        Message
  ----     ------     ----                  ----                                        -------
  Normal   Scheduled  3m15s                 default-scheduler                           Successfully assigned hub23/hub23-cert-manager-698b56f675-m2tmf to aks-nodepool1-40514338-vmss000000
  Normal   Pulled     98s (x5 over 3m14s)   kubelet, aks-nodepool1-40514338-vmss000000  Container image "quay.io/jetstack/cert-manager-controller:v0.11.0" already present on machine
  Normal   Created    98s (x5 over 3m14s)   kubelet, aks-nodepool1-40514338-vmss000000  Created container cert-manager
  Normal   Started    97s (x5 over 3m13s)   kubelet, aks-nodepool1-40514338-vmss000000  Started container cert-manager
  Warning  BackOff    86s (x10 over 3m12s)  kubelet, aks-nodepool1-40514338-vmss000000  Back-off restarting failed container
```

**Comment by sgibson91** [comment]
## Step 4

Enable ingress, annotations, hosts and TLS for hub and binder in `values.yaml` file:

```
  ingress:
    enabled: true
    annotations:
      # cert-manager provides a TLS secret
      # This will ask cert-manager to be configured with default values. It's better to configure default values.
      kubernetes.io/tls-acme: "true"
      # nginx-ingress controller to be explicitly utilised instead of "gce"
      # This is required to allow nginx-ingress-controller to function. This will override any cloud provided ingress controllers and use the one we choose to deploy, i.e. nginx.
      kubernetes.io/ingress.class: nginx
    hosts:
      - binder.hub23.turing.ac.uk
    tls:
      - secretName: binder-hub23-tls
        hosts:
          - binder.hub23.turing.ac.uk

  jupyterhub:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: nginx
      hosts:
        - hub.hub23.turing.ac.uk
      tls:
        - secretName: hub-hub23-tls
          hosts:
            - hub.hub23.turing.ac.uk
```

Switch BinderHub and JupyterHub to Cluster IPs:

```
  service:
    type: ClusterIP

  jupyterhub:
    proxy:
      service:
        # nodePorts:
        #   http: false
        type: ClusterIP
```

Perform helm upgrade:

```
cd hub23-chart && helm dependency update && cd ..
helm upgrade hub23 ./hub23-chart -f deploy/prod.yaml -f .secret/prod.yaml
```

```
UPGRADE FAILED
Error: Service "proxy-public" is invalid: [spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP', spec.ports[1].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'] && Service "binder" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
Error: UPGRADE FAILED: Service "proxy-public" is invalid: [spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP', spec.ports[1].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'] && Service "binder" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

Tried:

```
  service:
    nodePorts:
      http: false
    type: ClusterIP

  jupyterhub:
    proxy:
      service:
        nodePorts:
          http: false
        type: ClusterIP
```

But still repeated error.
